name: PlainUPnP CI

on:
  push:
    branches: [ develop, master, 'shortliving/**' ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install bundler dependencies
      run: bundler install
    - name: Test
      run: bundler exec fastlane test

